// packages/create-nalth/nalth-svelte/src/lib/SecurityBadge.svelte
<script lang="ts">
  export let score: number = 95

  $: scoreClass = score >= 90 ? 'excellent' : score >= 70 ? 'good' : 'needs-attention'
  $: statusLabel = score >= 90 ? 'Excellent' : score >= 70 ? 'Good' : 'Needs Attention'
  $: statusIcon = score >= 90 ? '✅' : score >= 70 ? '⚠️' : '❌'
</script>

<div class="nalth-security-badge">
  <span class="security-icon">🛡️</span>
  <div class="security-info">
    <span class="security-label">Security Score:</span>
    <span class="nalth-security-score {scoreClass}">{score}%</span>
    <span class="security-status">{statusLabel}</span>
  </div>
  <span class="status-icon {scoreClass}">{statusIcon}</span>
</div>

<style>
  .security-icon {
    font-size: 1.25rem;
  }

  .security-info {
    display: flex;
    align-items: center;
    gap: 0.5rem;
  }

  .security-label {
    font-size: 0.875rem;
    color: var(--nalth-text-muted);
  }

  .security-status {
    font-size: 0.75rem;
    padding: 0.25rem 0.5rem;
    border-radius: 0.375rem;
    background: var(--nalth-bg-secondary);
    color: var(--nalth-text-muted);
  }

  .status-icon {
    font-size: 1.125rem;
  }
</style>

// packages/create-nalth/nalth-react/src/components/SecurityBadge.tsx
import { Shield, CheckCircle, AlertTriangle, XCircle } from 'lucide-react'
import { cn } from '../lib/utils'

interface SecurityBadgeProps {
  score?: number
  className?: string
}

export function SecurityBadge({ score = 95, className }: SecurityBadgeProps) {
  const getScoreColor = (score: number) => {
    if (score >= 90) return 'text-green-500'
    if (score >= 70) return 'text-yellow-500'
    return 'text-red-500'
  }

  const getScoreIcon = (score: number) => {
    if (score >= 90) return <CheckCircle className="w-5 h-5 text-green-500" />
    if (score >= 70) return <AlertTriangle className="w-5 h-5 text-yellow-500" />
    return <XCircle className="w-5 h-5 text-red-500" />
  }

  const getScoreLabel = (score: number) => {
    if (score >= 90) return 'Excellent'
    if (score >= 70) return 'Good'
    return 'Needs Attention'
  }

  return (
    <div className={cn(
      'inline-flex items-center gap-3 px-4 py-2 rounded-lg border',
      'bg-card/50 border-border backdrop-blur-sm shadow-lg',
      className
    )}>
      <Shield className="w-5 h-5 text-primary" />
      <div className="flex items-center gap-2">
        <span className="text-sm font-medium text-muted-foreground">Security Score:</span>
        <span className={cn('text-lg font-bold', getScoreColor(score))}>
          {score}%
        </span>
        {getScoreIcon(score)}
      </div>
      <span className="text-xs text-foreground bg-secondary/50 px-2 py-1 rounded border border-border">
        {getScoreLabel(score)}
      </span>
    </div>
  )
}
